In [ ]:
import pandas as pd

bookings = pd.read_excel("../data/gl_posting.xlsx")
# bookings.loc[0, "Account"] = 1000000.01
# bookings = bookings.loc[:, ~bookings.columns.str.contains("^Unnamed")]
# bookings.to_excel("../data/gl_posting.xlsx", index=False)
bookings = pd.read_excel("../data/gl_posting.xlsx")
bookings

  Legal Entity Currency     Account
0          aaa      USD  1000000.01
1          bbb      CHF  1000000.13
2          ccc      EUR  1000000.20
3          aaa      USD  1000000.12
4          bbb      CHF  1000000.10
5          ccc      EUR  1000000.20

In [28]:
checked_output = pd.read_excel("../output/checked_output.xlsx")
checked_output

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Legal Entity,Currency,Account,check_results
0,0,0,0,0,aaa,USD,1000000.01,OK
1,1,1,1,1,bbb,CHF,1000000.13,OK
2,2,2,2,2,ccc,EUR,1000000.20,Mismatch: EUR should end with .02
3,3,3,3,3,aaa,USD,1000000.12,Mismatch: USD should end with .01
4,4,4,4,4,bbb,CHF,1000000.10,Mismatch: CHF should end with .13
5,5,5,5,5,ccc,EUR,1000000.20,Mismatch: EUR should end with .02

In [29]:
issues_bookings = pd.read_excel("../output/issues_bookings.xlsx")
issues_bookings

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Legal Entity,Currency,Account,check_results
0,2,2,2,2,ccc,EUR,1000000.20,Mismatch: EUR should end with .02
1,3,3,3,3,aaa,USD,1000000.12,Mismatch: USD should end with .01
2,4,4,4,4,bbb,CHF,1000000.10,Mismatch: CHF should end with .13
3,5,5,5,5,ccc,EUR,1000000.20,Mismatch: EUR should end with .02